### ISSUE TITLE
feedback from twitter

### ISSUE THREAD

**Issue by njtierney** [karthik/ddd#109]
https://twitter.com/nj_tierney/status/1218305120032546816

- [ ] deploy html via docs/index.html 
- [ ] look into [ETL package](https://github.com/beanumber/etl)
- [ ] "2.6 scripts could be more specific, - do you want a single script that takes the data in raw_data and outputs to a folder called data? Or is "all scripts + sufficient instructions" enough?" (from Matt Mack)

**Comment by njtierney** [comment]
And related threads: https://twitter.com/dataandme/status/1219681661874528256

**Comment by dschief001** [comment]
Hi!
my suggestions:

- page 6, 2.1 Readme: last two lines a few spelling mistakes
- reffering to Data dictionary, maybe you should stay with *codebook*?
- page 11, 2.3.2 second line it's, italic also bold! (find a structured layout for this and the following paragraph.
- page 12. "frictionless" -> spelling in citation?
- page 15 top paragraph, last line, should one share *.rds, .rda, ...* and so on, or not? clarify please!
- page 20: ...piggyback, **or a in serverless databases.** correct?
- page 21: citation for Zenodo?
- page: 25 (figure 7 A vs. B), there seems to be quite a bit of noise difference, if they do, mention a not reproduced "filtering/cleaning" step in the figure legend...

Otherwise keep up the good work guys!

**Comment by njtierney** [comment]
Thank you @dschief001 for your comments! Much appreciated!
